'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5466
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System
Namespace WebApp


	Partial Public Class TimeoutControl

		''' <summary>
		''' TimeoutPopup control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected TimeoutPopup As Global.DevExpress.Web.ASPxPopupControl.ASPxPopupControl

		''' <summary>
		''' PopupControlContentControl1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected PopupControlContentControl1 As Global.DevExpress.Web.ASPxPopupControl.PopupControlContentControl

		''' <summary>
		''' GlobalEvents control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected GlobalEvents As Global.DevExpress.Web.ASPxGlobalEvents.ASPxGlobalEvents

		''' <summary>
		''' KeepAliveHelper control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected KeepAliveHelper As Global.DevExpress.Web.ASPxCallback.ASPxCallback
	End Class
End Namespace
